### ISSUE TITLE
每次请求，都重新建了一个OkHttpClient？

### ISSUE THREAD

**Issue by RockyQu** [YuanClouds/Leopard#5]

**Comment by JessYanCoding** [comment]
正好想提 **Issues**,没想到已经有人提了,再叙述一次: 您好,框架文档写的很详细,不得不给个 **nice**,但我认真看了框架源码,发现每请求一次都会创建 **OkhttpClient.builder** 和 **Retrofit.builder** 和一系列只需要创建一次的对象,并且 **build** 后还会产生 **OkhttpClient** 和 **Retrofit** 对象在进行相应的请求,我自己写过一个集成化框架,也是用 Dagger 管理这些对象只初始化生成一次,请问你这样做出于什么考虑呢?（善意的提醒）

**Comment by DesignQu** [comment]
我就是在群里看了你说的，过来提的，哈哈

**Comment by Zhangxd77** [comment]
请问大家有优化好这个问题吗

**Comment by JessYanCoding** [comment]
@Zhangxd77 没, 这个库 2017 年 5 月份后就没更新过

**Comment by Zhangxd77** [comment]
能冒昧问下,后来你用别的哪个框架写的吗

**Comment by RockyQu** [comment]
@Zhangxd77 可以参考 @JessYanCoding 这位写的，他有一整套的框架，直接用

**Comment by JessYanCoding** [comment]
@Zhangxd77 https://github.com/JessYanCoding/MVPArms 我这个集成化框架有封装网络这块, 但不是纯粹的网络框架, 你可以借鉴下

**Comment by Zhangxd77** [comment]
我现在是需要做一个多任务可以断点续传下载,有进度回调这样的,我之前项目用的Retrofit,用的也比较熟,但是现在没找到合适的基于这个写的,https://github.com/jeasonlzy/okhttp-OkGo我看这个有,但是是okhttp的

**Comment by RockyQu** [comment]
要纯下载的？https://github.com/lingochamp/FileDownloader 看看这个

**Comment by Zhangxd77** [comment]
这个我也看了,看完以后没看到他网络用的什么,您知道么?

**Comment by JessYanCoding** [comment]
@Zhangxd77 兄弟, Retrofit 网络请求本来就用的就是 Okhttp, 所以封装下载这块的逻辑, 用 Okhttp 是没错的

**Comment by Zhangxd77** [comment]
不是..是他根本没用retrofit,我知道他是基于okhttp...还有我是女孩子

**Comment by RockyQu** [comment]
基本都是用Okhttp

**Comment by JessYanCoding** [comment]
@Zhangxd77 要不你加我们的QQ群, 301733278  ，很多人可以帮你

**Comment by Zhangxd77** [comment]
好!

**Comment by zjxuzhj** [comment]
群主撩妹技巧还是高

**Comment by CodeK1988** [comment]
😀 @JessYanCoding  是妹子就拉群么？ 瞅表脸
